### ISSUE TITLE
Code escaping not work

### ISSUE THREAD

**Issue by demon101** [wbb/wysibb#114]
write text "[b]test[/b]"
switch to bbcode mode
switch back
test text become to bold "test" without tags text

**Comment by wbb** [comment]
What wrong wysibb do? If you enter bbcodes and transform it to bbocde&back, this bbcodes should transform to wysiwyg mode. 

It is need for direct bbcodes enter.

**Comment by demon101** [comment]
Тут все не так однозначно. Пишу я просто текст, а при сохранение что-то вдруг стало тегами.
Например, если в висиви html редакторе ввести руками текст, содержащий теги, то они просто заэскейпятся. 

Конечно, ваша логика хороша для смайлов и прочего, но тоже большой вопрос, иногда такая автозамена делает из обычной пунктуации смайлы.
