### ISSUE TITLE
Cant submit form

### ISSUE THREAD

**Issue by mops1k** [wbb/wysibb#155]
Hi!
I make web application, where i need to use bbcodes and my choise of bb editors was wysibb, before i include it in project, form submitting working fine, after, when i push submit button, nothing going on. Browser i used is google chrome. I am not good in javascript and cant fix it by myself.

Some help? Thanks!

**Comment by mops1k** [comment]
After pushing submit button i get in console:
Set focus to WysiBB editor

**Comment by wbb** [comment]
Just call WysiBB API method before submit form: $("#editor")**.sync()**

**Comment by mops1k** [comment]
Thanks, working!
