### ISSUE TITLE
Youtube Video

### ISSUE THREAD

**Issue by HDVinnie** [wbb/wysibb#177]
Is this feature broken? Im using latest version from wysibb website and when I insert video it doesn't show. 

[Imgur](http://i.imgur.com/Yjgc7Bs.png)

[Imgur](http://i.imgur.com/C8uiUlu.jpg?1)

**Comment by HDVinnie** [comment]
anyone?

**Comment by djejaquino** [comment]
Is your website **https**?

**Comment by HDVinnie** [comment]
Yes I figured it out looking at the pending pull request. I wish someone would fork and take over development as it seems dead and this is a nice editor for most part
