### ISSUE TITLE
Conflict with bootstrap [color]

### ISSUE THREAD

**Issue by joelmiguelvalente** [wbb/WysiBB#198]
El conflicto: No puedo usar el color!

Cuando se usa bootstrap se genera un conflicto/error con **popper.min.js** del framework esto es lo que muestra
EJ:
`[color=null]el texto a dar color[/color]`
sale en púrpura, hay alguna forma de solucionarlo, ya que popper es necesario para que algunas funciones de bootstrap puedan seguir funcionando...como por ejemplo el modal!

**↓ Translation ↓**
The conflict: I can not use the color!

When using bootstrap a conflict / error is generated with **popper.min.js** of the framework this is what it shows
EJ:
`[color=null] the text to color[/color]`
comes out in purple, there is some way to fix it, since popper is necessary for some bootstrap functions to continue to work ... such as the modal!

**Comment by HDVinnie** [comment]
This project is long dead. I suggest finding a alternative.
