### ISSUE TITLE
<br>  Line Break Element not function after paste

### ISSUE THREAD

**Issue by kudataz** [wbb/wysibb#75]
i copied text from site like this.. with  Line Break Element
> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod 
> 
> tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis 

but after paste the result is.. without  Line Break Element
> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh > euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim 

can solve this admin  Vadim Dobroskok and wysibb team.. 
please ur help :dango:  & ASAP update script @wbb  too

**Comment by wbb** [comment]
It is happen because source html code has different of wysibb html format. Wysibb not guilty.
