### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by SiteSplat** [wbb/wysibb#89]
Is the project still maintained? I see lots and lots of questions not answered. Same thing on the support forum.
It would be nice to know what the roadmap is for this. If you someone opts to implement the editor on their projects, would be great to know if they are on their own for any issues or they can ask support for it.
Thanks!

**Comment by adaur** [comment]
I use it daily, it doesn't have major bugs except the double quote

**Comment by wbb** [comment]
The project is not dead & will develop.

**Comment by jartaud** [comment]
It's dead now!

**Comment by q8-hma** [comment]
Hello

we really like this project and we need update for it

any one can update it ??

thnx
