### ISSUE TITLE
Cursor don't move down, when I clicked Enter key in Safari on OS X.

### ISSUE THREAD

**Issue by vylgin** [wbb/wysibb#99]
If I click on the button Enter, a new text line is added, and the cursor don't move down in Safari on OS X (http://www.wysibb.com/demo).

**Comment by guysaq** [comment]
1+

**Comment by guysaq** [comment]
vylgin,
can you please let me know if you fixed it? 
i am still looking for fix for it

**Comment by vylgin** [comment]
I still did not fix it. I'm looking for too. If I find a solution, then write about it

**Comment by vylgin** [comment]
File jquery.wysibb.js contains
```javascript
//insert BR on press enter
this.$body.bind('keydown',$.proxy(function(e) {
	if (e.which == 13) {
		var isLi = this.isContain(this.getSelectNode(),'li');
		if (!isLi) {
			if (e.preventDefault) {e.preventDefault();}
				this.checkForLastBR(this.getSelectNode());
				this.insertAtCursor('<br/>',false);
			}
		}
},this));
```
I think we can solve the problem by refactor this code.

**Comment by chuve** [comment]
i have the same problem, any ideas?

**Comment by OliverIost** [comment]
Problem solved! Added the two lines described below.

execNativeCommand: function(cmd,param) { 

...

}else if (cmd=="insertHTML") { //fix webkit bug with insertHTML
				var sel = this.getSelection();
				var e = this.elFromString(param);
				var rng = (this.lastRange) ? this.lastRange:this.getRange();
				rng.deleteContents();
				rng.insertNode(e);
                                **rng.setStartAfter(e);**
                                **rng.setEndAfter(e);**
                                rng.collapse(false);
				sel.removeAllRanges();
				sel.addRange(rng);

**Comment by vylgin** [comment]
Thanks!

**Comment by wbb** [comment]
Fixed by Oliverlost. Thanks.
